import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*
        suppressHydrationWarning: Some browser extensions (e.g. Grammarly) inject attributes
        into the DOM (data-new-gr-c-s-check-loaded, data-gr-ext-installed) which mutate
        the server-rendered HTML before React hydrates. That causes hydration mismatch
        warnings. This attribute silences those warnings for the `<body>` and its
        descendants. Remove this after verifying no extensions or client-only code
        cause mismatches in a production environment.
      */}
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
